name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**' # Only trigger if changes are made inside the frontend folder

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies and verify build
        working-directory: ./frontend
        run: |
          npm install
          npm run build